version: '3'

services:
  # Serviço de backend
  backend:
    build:
      context: .
      dockerfile: backend-deploy/Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - PORT=80
    restart: always
    networks:
      - webfoto-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Serviço de frontend
  frontend:
    build:
      context: .
      dockerfile: frontend-deploy/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - webfoto-network

networks:
  webfoto-network:
    driver: bridge
